version: '3.8'

services:
  frontend:
    build:
      context: ./app  # Caminho para o diretório onde está o Dockerfile do front-end
    container_name: matematicanavida-frontend
    ports:
      - "3000:80"  # Expondo a porta 80 (do Nginx no container) para a 3000 localmente
    depends_on:
      - backend  # O front-end depende do back-end estar pronto antes de rodar
    networks:
      - app_network  # Rede compartilhada entre os serviços
    environment:
      - API_URL=http://backend:5000  # URL para a API do back-end

networks:
  app_network:
    driver: bridge
